extends SceneTree

# Iter 87 — replace procedural slash + dash + parry FX with PixelLab-
# generated sprite-sheet animations played via FxSprite.
#
# User feedback after the iter-85 fire + spawn-burst work: "None of them
# felt good. We need to get or generate effects. Especially for melee."
#
# 4 sprite sheets generated by PixelLab API:
#   slash_arc_sheet.png    — cyan-white curved energy slash arc
#   dash_impact_sheet.png  — radial cyan-white shockwave
#   parry_burst_sheet.png  — golden circular shield deflect
#   hit_spark_sheet.png    — small white impact spark (generated; not
#                             yet wired in iter-87, available for a
#                             follow-up to replace fx.gd's hit_spark)
#
# New FxSprite class loads each sheet + meta, builds SpriteFrames at
# runtime, plays the animation once via AnimatedSprite2D, self-frees.
# No manual squashing — scale is set on the node, frames render at
# native 64×64 resolution with nearest-neighbor scaling.
func _initialize() -> void:
	var ok := true

	# ═══ Generated sheets + metadata present ═══
	for name in ["slash_arc", "dash_impact", "parry_burst", "hit_spark"]:
		var sheet_path := "res://assets/fx/%s_sheet.png" % name
		var meta_path := "res://assets/fx/%s_meta.json" % name
		if not ResourceLoader.exists(sheet_path):
			push_error("FAIL: %s missing" % sheet_path)
			ok = false
		elif not FileAccess.file_exists(meta_path):
			push_error("FAIL: %s missing" % meta_path)
			ok = false
		else:
			var f := FileAccess.open(meta_path, FileAccess.READ)
			var meta = JSON.parse_string(f.get_as_text())
			f.close()
			if not (meta is Dictionary) or int(meta.get("frames", 0)) <= 0:
				push_error("FAIL: %s meta invalid (frames=%d)" % [name, int(meta.get("frames", 0))])
				ok = false
			else:
				print("OK %s sheet + meta (%d frames @ %s fps)" % [name, int(meta["frames"]), str(meta.get("fps", "?"))])

	# ═══ FxSprite class ═══
	var fxs := load("res://scripts/fx_sprite.gd")
	if fxs == null:
		push_error("FAIL: fx_sprite.gd failed to load")
		ok = false
	elif not fxs.has_method("spawn"):
		push_error("FAIL: FxSprite missing static spawn()")
		ok = false
	else:
		print("OK FxSprite class has static spawn()")

	# Runtime smoke — instantiate via spawn(), verify the AnimatedSprite2D
	# is built correctly + parented to host.
	if fxs != null and fxs.has_method("spawn"):
		var host := Node2D.new()
		root.add_child(host)
		var fx = fxs.spawn(host, Vector2(640, 384), "slash_arc", {})
		if fx == null:
			push_error("FAIL: FxSprite.spawn returned null for slash_arc")
			ok = false
		elif not (fx is AnimatedSprite2D):
			push_error("FAIL: FxSprite is not an AnimatedSprite2D, got %s" % fx.get_class())
			ok = false
		else:
			print("OK FxSprite.spawn returns AnimatedSprite2D parented to host")
			# Verify SpriteFrames was built with the right number of frames.
			if fx.sprite_frames == null:
				push_error("FAIL: FxSprite.sprite_frames not built")
				ok = false
			elif not fx.sprite_frames.has_animation("play"):
				push_error("FAIL: SpriteFrames missing 'play' animation")
				ok = false
			else:
				var frame_count: int = fx.sprite_frames.get_frame_count("play")
				if frame_count <= 0:
					push_error("FAIL: SpriteFrames 'play' animation has 0 frames")
					ok = false
				else:
					print("OK SpriteFrames 'play' has %d frames" % frame_count)

	# ═══ Procedural slash + parry_pulse files DELETED ═══
	for path in [
		"res://scripts/slash_arc.gd",
		"res://scenes/fx/slash_arc.tscn",
		"res://scripts/parry_pulse.gd",
		"res://scenes/fx/parry_pulse.tscn",
	]:
		if ResourceLoader.exists(path):
			push_error("FAIL: %s should be deleted but still exists" % path)
			ok = false
	if ok:
		print("OK procedural slash_arc + parry_pulse files deleted")

	# ═══ dash_impact KEPT (SOUL_BURST reuses it as relic placeholder) ═══
	if not ResourceLoader.exists("res://scripts/dash_impact.gd"):
		push_error("FAIL: dash_impact.gd should still exist (SOUL_BURST relic reuse)")
		ok = false
	elif not ResourceLoader.exists("res://scenes/fx/dash_impact.tscn"):
		push_error("FAIL: dash_impact.tscn should still exist (SOUL_BURST relic reuse)")
		ok = false
	else:
		print("OK dash_impact.gd + .tscn retained for SOUL_BURST relic reuse")

	# ═══ Call sites use FxSprite ═══
	var sf_src := FileAccess.get_file_as_string("res://scripts/screen_flash.gd")
	if not sf_src.contains("FxSprite.spawn") or not sf_src.contains("\"slash_arc\""):
		push_error("FAIL: screen_flash.gd doesn't FxSprite.spawn the slash_arc sheet")
		ok = false
	else:
		print("OK screen_flash.gd spawns slash_arc via FxSprite")

	# screen_flash should no longer preload SLASH_ARC_SCENE.
	if sf_src.contains("SLASH_ARC_SCENE: PackedScene"):
		push_error("FAIL: screen_flash.gd still preloads SLASH_ARC_SCENE")
		ok = false
	else:
		print("OK screen_flash.gd: SLASH_ARC_SCENE preload removed")

	var main_src := FileAccess.get_file_as_string("res://scripts/main.gd")
	if not main_src.contains("FxSprite.spawn") or not main_src.contains("\"dash_impact\""):
		push_error("FAIL: main.gd doesn't FxSprite.spawn the dash_impact sheet")
		ok = false
	else:
		print("OK main.gd spawns dash_impact via FxSprite")

	# main.gd should no longer preload DASH_IMPACT_SCENE.
	if main_src.contains("DASH_IMPACT_SCENE: PackedScene"):
		push_error("FAIL: main.gd still preloads DASH_IMPACT_SCENE for the dash strike")
		ok = false
	else:
		print("OK main.gd: DASH_IMPACT_SCENE preload removed")

	var hero_src := FileAccess.get_file_as_string("res://scripts/hero.gd")
	if not (hero_src.contains("FxSpriteHelper.spawn") or hero_src.contains("FxSprite.spawn")) \
			or not hero_src.contains("\"parry_burst\""):
		push_error("FAIL: hero.gd doesn't FxSprite.spawn the parry_burst sheet")
		ok = false
	else:
		print("OK hero.gd spawns parry_burst via FxSprite")

	# hero.gd should no longer preload PARRY_PULSE_SCENE.
	if hero_src.contains("PARRY_PULSE_SCENE  = preload"):
		push_error("FAIL: hero.gd still preloads PARRY_PULSE_SCENE")
		ok = false
	else:
		print("OK hero.gd: PARRY_PULSE_SCENE preload removed")

	if ok:
		print("=== ITER 87 INTEGRATION PASSED ===")
	else:
		print("=== ITER 87 INTEGRATION FAILED ===")
	quit(0 if ok else 1)
